# laravel.yml (Railway)
build:
  base: php:8.1-cli
  script:
    - composer install --optimize-autoloader --no-dev
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
start:
  command: php artisan serve --host=0.0.0.0 --port=5000
